### ISSUE TITLE
fix: Input 컴포넌트 ref 사용하여 접근하려 할 때 에러가 발생함.

### ISSUE THREAD

**Issue by kangju2000** [Breaking-Dope/breaking-frontend#59]
## 버그 발생 내용

`
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
`
부모 컴포넌트에서 자식 컴포넌트의 DOM 요소를 접근할 때는 forwardRef를 사용하여 접근해야한다고 합니다. 
참조 링크 : https://sambalim.tistory.com/151
## 버그 발생 트리거

Input 컴포넌트에 useRef 훅을 ref로 할당하고 접근하려 할 때 에러가 발생했습니다.

**Comment by Yoon-Hae-Min** [comment]
또 에러가 터졌군요 ㅋㅋㅋㅋ
